name: PostgreSQL Backup

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
     gpgkey: ${{secrets.GPG_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          mkdir secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$gpgkey" --output secrets/key.pem key.pem.gpg
          chmod 600 "secrets/key.pem"
          
      
     
      - name: SET version to gitenv
        run: echo "backupversion=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: URL Encode Password
        id: encode_password
        run: echo "ENCODED_PASSWORD=$(python3 -c 'import urllib.parse; print(urllib.parse.quote(\"${{ secrets.PG_PASSWORD }}\"))')" >> $GITHUB_ENV

      - name: Construct Database URL
        run: echo "DATABASE_URL=postgresql://${{ secrets.PG_USER }}:$ENCODED_PASSWORD@${{ secrets.SERVER_IP }}/muhammaddev" >> $GITHUB_ENV

      - name: CREATE A BACKUP 
        run: |
          ssh -o StrictHostKeyChecking=No -tt -i "secrets/key.pem" ${{secrets.SERVER_USER}}@'${{secrets.SERVER_IP}}' ' pg_dump  ${{env.DATABASE_URL}} >> ~/backups/${{env.backupversion}}'

      - name: COPY BACKUP
        run: |
          mkdir backups
          scp  root@${{secrets.SERVER_IP}}~/backups/${{env.backupversion}}' ./backups



      - name: Commit and push backup
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add backups/${{env.backupversion}}
          git commit -m "Database backup for $(date +'%F') version ${{env.backupversion}}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
